#pragma once

#include "sdkconfig.h"

/* Board camera pins now come from the selected BSP (bsp_camera_start owns
 * reset/pwdn/xclk/power). Only the no-BSP case needs a static pin table, which
 * lives in the customized board header — edit it for a bare/custom board. The
 * interface-common macros below (device path, SCCB freq) are board-agnostic. */
#if CONFIG_BSP_SELECT_NONE
#include "boards/customized/example_video_common_board.h"
#endif

#if CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP
#define MEDIA_STREAM_SCCB_I2C_PORT_INIT_BY_APP              CONFIG_MEDIA_STREAM_SCCB_I2C_PORT_INIT_BY_APP
#endif /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */

/**
 * @brief MIPI-CSI camera sensor common configuration
 */
#if CONFIG_MEDIA_STREAM_ENABLE_MIPI_CSI_CAM_SENSOR
#define MEDIA_STREAM_ENABLE_MIPI_CSI_CAM_SENSOR              1
#if CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP
#define MEDIA_STREAM_MIPI_CSI_SCCB_I2C_PORT                  MEDIA_STREAM_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */
#define MEDIA_STREAM_MIPI_CSI_SCCB_I2C_PORT                  CONFIG_MEDIA_STREAM_MIPI_CSI_SCCB_I2C_PORT
#endif /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */

#define MEDIA_STREAM_MIPI_CSI_SCCB_I2C_FREQ                  CONFIG_MEDIA_STREAM_MIPI_CSI_SCCB_I2C_FREQ

#if CONFIG_MEDIA_STREAM_ENABLE_MIPI_CSI_CAM_MOTOR
#define MEDIA_STREAM_ENABLE_MIPI_CSI_CAM_MOTOR              1
#if CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP
#define MEDIA_STREAM_MIPI_CSI_CAM_MOTOR_SCCB_I2C_PORT       MEDIA_STREAM_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */
#define MEDIA_STREAM_MIPI_CSI_CAM_MOTOR_SCCB_I2C_PORT       CONFIG_MEDIA_STREAM_MIPI_CSI_CAM_MOTOR_SCCB_I2C_PORT
#endif /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */

#define MEDIA_STREAM_MIPI_CSI_CAM_MOTOR_SCCB_I2C_FREQ       CONFIG_MEDIA_STREAM_MIPI_CSI_CAM_MOTOR_SCCB_I2C_FREQ
#endif /* CONFIG_MEDIA_STREAM_ENABLE_MIPI_CSI_CAM_MOTOR */
#endif /* CONFIG_MEDIA_STREAM_ENABLE_MIPI_CSI_CAM_SENSOR */

/**
 * @brief DVP camera sensor common configuration
 */
#if CONFIG_MEDIA_STREAM_ENABLE_DVP_CAM_SENSOR
#define MEDIA_STREAM_ENABLE_DVP_CAM_SENSOR                   1
#if CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP
#define MEDIA_STREAM_DVP_SCCB_I2C_PORT                       MEDIA_STREAM_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */
#define MEDIA_STREAM_DVP_SCCB_I2C_PORT                       CONFIG_MEDIA_STREAM_DVP_SCCB_I2C_PORT
#endif /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */

#define MEDIA_STREAM_DVP_SCCB_I2C_FREQ                       CONFIG_MEDIA_STREAM_DVP_SCCB_I2C_FREQ


/**
 * @brief DVP clock frequency configuration
 */
#if (defined(MEDIA_STREAM_DVP_XCLK_PIN) && MEDIA_STREAM_DVP_XCLK_PIN >= 0)
#define MEDIA_STREAM_DVP_XCLK_FREQ                           CONFIG_MEDIA_STREAM_DVP_XCLK_FREQ
#else
#define MEDIA_STREAM_DVP_XCLK_FREQ                           0
#endif /* MEDIA_STREAM_DVP_XCLK_PIN >= 0 */
#endif /* CONFIG_MEDIA_STREAM_ENABLE_DVP_CAM_SENSOR */

/**
 * @brief SPI camera sensor common configuration
 */
#if CONFIG_MEDIA_STREAM_ENABLE_SPI_CAM_0_SENSOR
#if CONFIG_MEDIA_STREAM_SPI_CAM_0_INTERFACE_SPI
#define MEDIA_STREAM_SPI_CAM_0_INTERFACE                     ESP_CAM_CTLR_SPI_CAM_INTF_SPI
#elif CONFIG_MEDIA_STREAM_SPI_CAM_0_INTERFACE_PARLIO
#define MEDIA_STREAM_SPI_CAM_0_INTERFACE                     ESP_CAM_CTLR_SPI_CAM_INTF_PARLIO
#endif /* CONFIG_MEDIA_STREAM_SPI_CAM_0_INTERFACE_SPI */

#if CONFIG_MEDIA_STREAM_SPI_CAM_0_IO_MODE_2BIT
#define MEDIA_STREAM_SPI_CAM_0_IO_MODE                       ESP_CAM_CTLR_SPI_CAM_IO_MODE_2BIT
#else /* CONFIG_MEDIA_STREAM_SPI_CAM_0_IO_MODE_2BIT */
#define MEDIA_STREAM_SPI_CAM_0_IO_MODE                       ESP_CAM_CTLR_SPI_CAM_IO_MODE_1BIT
#endif /* CONFIG_MEDIA_STREAM_SPI_CAM_0_IO_MODE_2BIT */

#define MEDIA_STREAM_ENABLE_SPI_CAM_SENSOR                   1
#define MEDIA_STREAM_ENABLE_SPI_CAM_0_SENSOR                 1
#if CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP
#define MEDIA_STREAM_SPI_CAM_0_SCCB_I2C_PORT                 MEDIA_STREAM_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */
#define MEDIA_STREAM_SPI_CAM_0_SCCB_I2C_PORT                 CONFIG_MEDIA_STREAM_SPI_CAM_0_SCCB_I2C_PORT
#endif /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */
#define MEDIA_STREAM_SPI_CAM_0_SCCB_I2C_FREQ                 CONFIG_MEDIA_STREAM_SPI_CAM_0_SCCB_I2C_FREQ

/**
 * @brief SPI camera sensor SPI port configuration
 */
#define MEDIA_STREAM_SPI_CAM_0_SPI_PORT                      CONFIG_MEDIA_STREAM_SPI_CAM_0_SPI_PORT

/**
 * @brief SPI camera sensor clock resource configuration
 */
#if CONFIG_MEDIA_STREAM_SPI_CAM_0_XCLK_USE_LEDC
#define MEDIA_STREAM_SPI_CAM_0_XCLK_RESOURCE                 ESP_CAM_SENSOR_XCLK_LEDC
#elif CONFIG_MEDIA_STREAM_SPI_CAM_0_XCLK_USE_CLOCK_ROUTER
#define MEDIA_STREAM_SPI_CAM_0_XCLK_RESOURCE                 ESP_CAM_SENSOR_XCLK_ESP_CLOCK_ROUTER
#endif /* CONFIG_MEDIA_STREAM_SPI_CAM_0_XCLK_USE_LEDC */

#if defined(MEDIA_STREAM_SPI_CAM_0_XCLK_PIN) && MEDIA_STREAM_SPI_CAM_0_XCLK_PIN >= 0
#define MEDIA_STREAM_SPI_CAM_0_XCLK_FREQ                     CONFIG_MEDIA_STREAM_SPI_CAM_0_XCLK_FREQ
#else
#define MEDIA_STREAM_SPI_CAM_0_XCLK_FREQ                     0
#endif /* MEDIA_STREAM_SPI_CAM_0_XCLK_PIN >= 0 */

#if CONFIG_MEDIA_STREAM_SPI_CAM_0_XCLK_USE_LEDC
#define MEDIA_STREAM_SPI_CAM_0_XCLK_TIMER                    CONFIG_MEDIA_STREAM_SPI_CAM_0_XCLK_TIMER
#define MEDIA_STREAM_SPI_CAM_0_XCLK_TIMER_CHANNEL            CONFIG_MEDIA_STREAM_SPI_CAM_0_XCLK_TIMER_CHANNEL
#endif /* CONFIG_MEDIA_STREAM_SPI_CAM_XCLK_USE_LEDC */

#if CONFIG_MEDIA_STREAM_ENABLE_SPI_CAM_1_SENSOR
#define MEDIA_STREAM_ENABLE_SPI_CAM_1_SENSOR                 1
#if CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP
#define MEDIA_STREAM_SPI_CAM_1_SCCB_I2C_PORT                 MEDIA_STREAM_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */
#define MEDIA_STREAM_SPI_CAM_1_SCCB_I2C_PORT                 CONFIG_MEDIA_STREAM_SPI_CAM_1_SCCB_I2C_PORT
#endif /* CONFIG_MEDIA_STREAM_SCCB_I2C_INIT_BY_APP */
#define MEDIA_STREAM_SPI_CAM_1_SCCB_I2C_FREQ                 CONFIG_MEDIA_STREAM_SPI_CAM_1_SCCB_I2C_FREQ

#define MEDIA_STREAM_SPI_CAM_1_SPI_PORT                      CONFIG_MEDIA_STREAM_SPI_CAM_1_SPI_PORT

#if CONFIG_MEDIA_STREAM_SPI_CAM_1_XCLK_USE_LEDC
#define MEDIA_STREAM_SPI_CAM_1_XCLK_RESOURCE                 ESP_CAM_SENSOR_XCLK_LEDC
#elif CONFIG_MEDIA_STREAM_SPI_CAM_1_XCLK_USE_CLOCK_ROUTER
#define MEDIA_STREAM_SPI_CAM_1_XCLK_RESOURCE                 ESP_CAM_SENSOR_XCLK_ESP_CLOCK_ROUTER
#endif /* CONFIG_MEDIA_STREAM_SPI_CAM_1_XCLK_USE_LEDC */

#if defined(MEDIA_STREAM_SPI_CAM_1_XCLK_PIN) && MEDIA_STREAM_SPI_CAM_1_XCLK_PIN >= 0
#define MEDIA_STREAM_SPI_CAM_1_XCLK_FREQ                     CONFIG_MEDIA_STREAM_SPI_CAM_1_XCLK_FREQ
#else
#define MEDIA_STREAM_SPI_CAM_1_XCLK_FREQ                     0
#endif /* MEDIA_STREAM_SPI_CAM_1_XCLK_PIN >= 0 */

#if CONFIG_MEDIA_STREAM_SPI_CAM_1_XCLK_USE_LEDC
#define MEDIA_STREAM_SPI_CAM_1_XCLK_TIMER                    CONFIG_MEDIA_STREAM_SPI_CAM_1_XCLK_TIMER
#define MEDIA_STREAM_SPI_CAM_1_XCLK_TIMER_CHANNEL            CONFIG_MEDIA_STREAM_SPI_CAM_1_XCLK_TIMER_CHANNEL
#endif /* CONFIG_MEDIA_STREAM_SPI_CAM_1_XCLK_USE_LEDC */
#endif /* CONFIG_MEDIA_STREAM_ENABLE_SPI_CAM_1_SENSOR */
#endif /* CONFIG_MEDIA_STREAM_ENABLE_SPI_CAM_0_SENSOR */

/**
 * @brief USB-UVC camera sensor common configuration
 */
#if CONFIG_MEDIA_STREAM_ENABLE_USB_UVC_CAM_SENSOR
#define MEDIA_STREAM_ENABLE_USB_UVC_CAM_SENSOR               1
#endif

/**
 * @brief Example camera device path configuration
 */
#if MEDIA_STREAM_ENABLE_USB_UVC_CAM_SENSOR
/* Ahead of CSI deliberately: MIPI-CSI is `default y`, so a board that selects UVC
 * would otherwise keep opening /dev/video0 instead of the UVC node /dev/video40. */
#define MEDIA_STREAM_CAM_DEV_PATH                            ESP_VIDEO_USB_UVC_DEVICE_NAME(0)
#elif MEDIA_STREAM_ENABLE_MIPI_CSI_CAM_SENSOR
#define MEDIA_STREAM_CAM_DEV_PATH                            ESP_VIDEO_MIPI_CSI_DEVICE_NAME
#elif MEDIA_STREAM_ENABLE_DVP_CAM_SENSOR
#define MEDIA_STREAM_CAM_DEV_PATH                            ESP_VIDEO_DVP_DEVICE_NAME
#elif MEDIA_STREAM_ENABLE_SPI_CAM_SENSOR
#define MEDIA_STREAM_CAM_DEV_PATH                            ESP_VIDEO_SPI_DEVICE_NAME
#else
#define MEDIA_STREAM_CAM_DEV_PATH                            ESP_VIDEO_SPI_DEVICE_NAME
#endif /* CONFIG_MEDIA_STREAM_ENABLE_MIPI_CSI_CAM_SENSOR */
